[package]
name = "zygisk"
version = "0.2.0"
edition = "2021"
authors = [
    "Kazurin Nanako <71819243+Kazurin-775@users.noreply.github.com>",
    "Paskal Sitepu <rmnscnce@ya.ru>",
]

[dependencies]
bitflags = "2.4"
jni = "0.21"
libc = "0.2"
